### ISSUE TITLE
Reuse request

### ISSUE THREAD

**Issue by andrew-ares** [DotIN13/plainwhite-wannaexpresso.com#1]
@DotIN13 你好👋，无意之中发现了你的站点，不得不说，很棒的博客👍！

我在想，如果你不介意的话，我能使用你的博客主题吗，非常感谢！

**Comment by DotIN13** [comment]
Sorry for replying to your request after almost a month. You can reuse the blog framework of course under the MIT license, and welcome!

BTW, the credit of the base theme goes to samarsault's [plainwhite-jekyll](https://github.com/samarsault/plainwhite-jekyll).
